#
# Include this file in your .gitlab-ci.yml file to automate & integrate Checkmarx security scans.
#
# These variables can be overridden in your .gitlab-ci.yml file or as envionrment variables.
#
# Find more documentation at: https://checkmarx.com/resource/documents/en/34965-68722-checkmarx-one-gitlab-integration.html
#

variables:
    CX_BRANCH_NAME: "${CI_COMMIT_REF_NAME}"
    CX_PROJECT_NAME: "$CI_PROJECT_NAME"
    CX_BASE_URI: ${CX_BASE_URI}
    CX_TENANT: ${CX_TENANT}
    CX_CLIENT_ID: ${CX_CLIENT_ID}
    CX_CLIENT_SECRET: ${CX_CLIENT_SECRET}
    CX_ADDITIONAL_PARAMS: ""
    CX_FILE_FILTERS: ""
    CHECKMARX_DOCKER_IMAGE: "ast-cli"

checkmarx-scan:
  stage: test
  image:
    name: checkmarx/${CHECKMARX_DOCKER_IMAGE}
    entrypoint: ['']
  script:
    - eval "args=(${CX_ADDITIONAL_PARAMS})"
    - >-
      /app/bin/cx
      scan create
      --project-name ${CX_PROJECT_NAME}
      --file-source '.'
      --scan-info-format 'json'
      --branch ${CX_BRANCH_NAME}
      --agent 'Gitlab' 
      --file-filter "${CX_FILE_FILTERS}"
      "${args[@]}"
